%% init_tricanter_params.m — вешается на Model Settings > Callbacks > InitFcn

% 1. Структура констант
p = struct( ...
    'Rd',      0.040,  'Rw',      0.0287, ...
    'Wsc',     0.025,  'Lpond',   0.17,   'alpha',   7.0,  'Lsep', 0.0, ...
    'n',       25,     'J',       40, ...
    'rho_s',   2720.0, 'rho_w',   998.0,  'rho_o',   870.0, ...
    'mu_s',    0.25,   'phi_sed', 0.45,   'phi_ref', 0.13,  'phi_max', 0.64, ...
    'u_conv',  0.57, ...
    'bs', 3.0, 'rrsb', false, ...
    'd50',     3.0e-6, 'bw', 2.0);

% 2. Bus-объект (описывает типы полей)
busInfo = Simulink.Bus.createObject(p);
BusTricParams = evalin('base', busInfo.busName);
assignin('base', 'BusTricParams', BusTricParams);
evalin('base', ['clear ' busInfo.busName]);

% 3. Parameter поверх struct, типизированный этим bus-ом
TricParams = Simulink.Parameter(p);
TricParams.DataType = 'Bus: BusTricParams';
TricParams.CoderInfo.StorageClass = 'Auto';

assignin('base', 'TricParams', TricParams);

inp = struct( ...
    'eps_o',  0.60, ...
    'eps_wd', 0.08, ...
    'Ro',     0.028, ...
    'eps_w',  0.30, ...   % убедитесь, что провод называется eps_w, а не eps_wf
    'eps_s',  0.02, ...
    'Rw',     0.0287, ...
    'dn',     10.0, ...
    'Q',      30/3.6e6, ...
    'x50',    1.5e-6, ...
    'C',      1500.0);

busInfo2 = Simulink.Bus.createObject(inp);
BusTricInputs = evalin('base', busInfo2.busName);
assignin('base', 'BusTricInputs', BusTricInputs);
evalin('base', ['clear ' busInfo2.busName]);

geo = struct( ...
    'omega', 0, ...
    'beta', 0, ...
    'Lax', 0, ...
    'L_cone', 0, ...
    'f_clar', 0, ...
    'u_ax', 0, ...
    'has_oil', false, ...
    'r_i', 0, ...
    'Qo', 0, ...
    'Qw', 0);

busInfo3 = Simulink.Bus.createObject(geo);
BusTricGeo = evalin('base', busInfo3.busName);
assignin('base', 'BusTricGeo', BusTricGeo);
evalin('base', ['clear ' busInfo3.busName]);